name: regru
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Build app
        run: npm run build
      # - name: Copy api
      #   run: sudo cp -rf /home/runner/work/quasar-test/quasar-test/api /home/runner/work/quasar-test/quasar-test/dist/spa/
      # - name: mkdir src
      #   run: sudo mkdir /home/runner/work/quasar-test/quasar-test/dist/spa/src
      # - name: mkdir assets
      #   run: sudo mkdir /home/runner/work/quasar-test/quasar-test/dist/spa/src/assets
      # - name: mkdir images
      #   run: sudo mkdir /home/runner/work/quasar-test/quasar-test/dist/spa/src/assets/images
      # - name: Copy images
      #   run: sudo cp -rf /home/runner/work/quasar-test/quasar-test/src/assets/images /home/runner/work/quasar-test/quasar-test/dist/spa/src/assets/
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/nm-master/nm-master/dist/
          remote: www/nm-master.ru
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}